on: [pull_request]

name: Continuous integration

jobs:

  test:
    name: Test & coverage
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - run: cargo llvm-cov --ignore-filename-regex "bin|.*test" --fail-under-functions 100 --fail-under-lines 100 --show-missing-lines